const v9 = {
	tutorial: true,
	cobblestone: 0,
	coal: 0,
	iron: 0,
	ironOre: 0,
	gold: 0,
	goldOre: 0,
	lapis: 0,
	diamond: 0,
	enchantedDiamond: 0,
	pickaxe: '<:Wooden_Pickaxe:817217441394196572>',
	axe: '<:Wooden_Axe:817217337261424650>',
	rod: '<:Wooden_Rod:816598231509237810>',
	startMine: true,
	ironMine: false,
	goldMine: false,
	lapisQua: false,
	diaSanct: false,
	mineLevel: 0,
	mineXp: 0,
	start: true,
	update: '9.0.0',
	updatingState: false,
	commonFish: 0,
	uncommonFish: 0,
	rareFish: 0,
	ultraRareFish: 0,
	legendaryFish: 0,
	fishLevel: 0,
	fishXp: 0,
	oakWood: 0,
	birchWood: 0,
	spruceWood: 0,
	jungleWood: 0,
	acaciaWood: 0,
	darkOakWood: 0,
	planks: 0,
	stick: 0,
	chopXp: 0,
	chopLevel: 0,
	forest: true,
	roofedForest: false,
	taiga: false,
	savannah: false,
	jungle: false,
	coins: 0,
	bank: 0,
	bankTier: 1,
	invCobblestoneMinion: 0,
	invCoalMinion: 0,
	invIronMinion: 0,
	invGoldMinion: 0,
	invLapisMinion: 0,
	invDiamondMinion: 0,
	invOakWoodMinion: 0,
	invBirchWoodMinion: 0,
	invDarkOakWoodMinion: 0,
	invSpruceWoodMinion: 0,
	invAcaciaWoodMinion: 0,
	invJungleWoodMinion: 0,
	enchantedGold: 0,
	enchantedGoldBlock: 0,
	placedMinions: [
		[
			'cobblestone minion',
			'invCobblestoneMinion',
			'i',
			'<:Placed_Cobblestone_Minion:887166926948798484>',
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			1650422911577,
			'cobblestone minion'
		]
	],
	blockOfCoal: 0,
	enchantedBread: 0,
	enchantedCharcoal: 0,
	enchantedCoal: 0,
	enchantedLavaBucket: 0,
	netWorth: 0,
	enchantedCobblestone: 0,
	pureDiamond: 0,
	enchantedIron: 0,
	enchantedLapis: 0,
	enchantedOakWood: 0,
	enchantedBirchWood: 0,
	enchantedDarkOakWood: 0,
	enchantedSpruceWood: 0,
	enchantedAcaciaWood: 0,
	enchantedJungleWood: 0,
	redstone: 0,
	enchantedRedstone: 0,
	compactor: 0,
	superCompactor: 0,
	invRedstoneMinion: 0,
	tutorials: { minion: false, dices: false, highlow: false, scratchoff: false },
	gambleStats: {
		dices: { moneyWon: 0, moneyLost: 0, totalWins: 0, totalLoses: 0 },
		scratchoff: { moneyWon: 0, moneyLost: 0, totalWins: 0, totalLoses: 0 }
	},
	enchantedRedstoneBlock: 0,
	blockofcoal: 0,
	commandUses: {},
	redsMine: false,
	sword: {
		name: 'Wooden sword',
		keyName: 'woodenSword',
		emoji: '<:Wooden_Sword:945957542280970300>',
		baseDamage: 20,
		enchantments: []
	},
	woodenSword: 0,
	stoneSword: 0,
	ironSword: 0,
	goldSword: 0,
	diamondSword: 0,
	aspectOfTheSpiritButterfly: 0,
	spiritButterfly: 0,
	woodenPickaxe: 0,
	stonePickaxe: 0,
	ironPickaxe: 0,
	goldPickaxe: 0,
	diamondPickaxe: 0,
	woodenAxe: 0,
	stoneAxe: 0,
	ironAxe: 0,
	goldAxe: 0,
	diamondAxe: 0,
	combatLevel: 0,
	combatXp: 0,
	activeItems: [],
	fourLeafClover: 0,
	stopwatch: 0,
	achievements: [
		{ id: `use1kCmds`, done: false },
		{ id: `use10kCmds`, done: false },
		{ id: `use50kCmds`, done: false },
		{ id: `use100kCmds`, done: false }
	],
	adventure: {},
	settings: [
		{ setting: 'hideFromLb', value: false },
		{ setting: 'fightNerd', value: false },
		{ setting: 'voteReady', value: false }
	],
	daily: {
		lastClaimed: 0,
		streak: 0
	},
	enclosure: 'cow',
	piggyBank: 0,
	crackedPiggyBank: 0,
	brokenPiggyBank: 0,
	rawPorkchop: 0,
	enchantedPork: 0,
	enchantedGrilledPork: 0,
	rawChicken: 0,
	enchantedRawChicken: 0,
	rawBeef: 0,
	enchantedRawBeef: 0,
	rawMutton: 0,
	enchantedMutton: 0,
	enchantedCookedMutton: 0
};

const v10 = {
	axe: '<:Wooden_Axe:817217337261424650>',
	pickaxe: '<:Wooden_Pickaxe:817217441394196572>',
	rod: '<:Wooden_Rod:816598231509237810>',
	cobblestone: 0,
	coal: 0,
	ironOre: 0,
	iron: 0,
	goldOre: 0,
	gold: 0,
	lapis: 0,
	diamond: 0,
	pureDiamond: 0,
	startMine: true,
	ironMine: false,
	goldMine: false,
	lapisQua: false,
	diaSanct: false,
	redsMine: false,
	mineLevel: 0,
	mineXp: 0,
	fishLevel: 0,
	fishXp: 0,
	chopLevel: 0,
	chopXp: 0,
	oakWood: 0,
	birchWood: 0,
	darkOakWood: 0,
	spruceWood: 0,
	acaciaWood: 0,
	jungleWood: 0,
	planks: 0,
	stick: 0,
	forest: true,
	roofedForest: false,
	taiga: false,
	savannah: false,
	jungle: false,
	commonFish: 0,
	uncommonFish: 0,
	rareFish: 0,
	ultraRareFish: 0,
	legendaryFish: 0,
	coins: 0,
	bank: 0,
	netWorth: 0,
	invOakWoodMinion: 0,
	invBirchWoodMinion: 0,
	invDarkOakWoodMinion: 0,
	invSpruceWoodMinion: 0,
	invAcaciaWoodMinion: 0,
	invJungleWoodMinion: 0,
	invCobblestoneMinion: 0,
	invCoalMinion: 0,
	invIronMinion: 0,
	invGoldMinion: 0,
	invDiamondMinion: 0,
	invLapisMinion: 0,
	placedMinions: [
		[
			'cobblestone minion',
			'invCobblestoneMinion',
			'i',
			'<:Placed_Cobblestone_Minion:887166926948798484>',
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			1650340892852,
			'cobblestone minion'
		]
	],
	bankTier: 1,
	enchantedGold: 0,
	enchantedGoldBlock: 0,
	blockOfCoal: 0,
	enchantedBread: 0,
	enchantedCharcoal: 0,
	enchantedCoal: 0,
	enchantedLavaBucket: 0,
	enchantedCobblestone: 0,
	enchantedIron: 0,
	enchantedLapis: 0,
	enchantedDiamond: 0,
	enchantedOakWood: 0,
	enchantedBirchWood: 0,
	enchantedDarkOakWood: 0,
	enchantedSpruceWood: 0,
	enchantedAcaciaWood: 0,
	enchantedJungleWood: 0,
	redstone: 0,
	enchantedRedstone: 0,
	compactor: 0,
	superCompactor: 0,
	invRedstoneMinion: 0,
	tutorials: { minion: false, dices: false, highlow: false, scratchoff: false },
	gambleStats: {
		dices: { moneyWon: 0, moneyLost: 0, totalWins: 0, totalLoses: 0 },
		scratchoff: { moneyWon: 0, moneyLost: 0, totalWins: 0, totalLoses: 0 }
	},
	sword: {
		name: 'Wooden sword',
		keyName: 'woodenSword',
		emoji: '<:Wooden_Sword:945957542280970300>',
		baseDamage: 20,
		enchantments: []
	},
	woodenSword: 0,
	stoneSword: 0,
	ironSword: 0,
	goldSword: 0,
	diamondSword: 0,
	aspectOfTheSpiritButterfly: 0,
	spiritButterfly: 0,
	woodenPickaxe: 0,
	stonePickaxe: 0,
	ironPickaxe: 0,
	goldPickaxe: 0,
	diamondPickaxe: 0,
	woodenAxe: 0,
	stoneAxe: 0,
	ironAxe: 0,
	goldAxe: 0,
	diamondAxe: 0,
	combatLevel: 0,
	combatXp: 0,
	activeItems: [],
	fourLeafClover: 0,
	stopwatch: 0,
	achievements: [
		{
			id: `use1kCmds`,
			done: false
		},
		{
			id: `use10kCmds`,
			done: false
		},
		{
			id: `use50kCmds`,
			done: false
		},
		{
			id: `use100kCmds`,
			done: false
		}
	],
	adventure: {},
	commandUses: { dev: 1 },
	start: true,
	update: '10.1.0',
	enclosure: 'cow',
	piggyBank: 0,
	crackedPiggyBank: 0,
	brokenPiggyBank: 0,
	rawPorkchop: 0,
	enchantedPork: 0,
	enchantedGrilledPork: 0,
	rawChicken: 0,
	enchantedRawChicken: 0,
	rawBeef: 0,
	enchantedRawBeef: 0,
	rawMutton: 0,
	enchantedMutton: 0,
	enchantedCookedMutton: 0,
	settings: [
		{ setting: 'hideFromLb', value: false },
		{ setting: 'fightNerd', value: false },
		{ setting: 'voteReady', value: false }
	],
	daily: { lastClaimed: 0, streak: 0 },
	adventureTicket: 0,
	hiltOfTheSeas: 0,
	firstFragmentOfTheSeas: 0,
	secondFragmentOfTheSeas: 0,
	aspectOfTheSeas: 0,
	dummy: 0,
	helmet: null,
	chestplate: null,
	leggings: null,
	boots: null,
	leatherHelmet: 0,
	leatherChestplate: 0,
	leatherLeggings: 0,
	leatherBoots: 0,
	ironHelmet: 0,
	ironChestplate: 0,
	ironLeggings: 0,
	ironBoots: 0,
	goldHelmet: 0,
	goldChestplate: 0,
	goldLeggings: 0,
	goldBoots: 0,
	diamondHelmet: 0,
	diamondChestplate: 0,
	diamondLeggings: 0,
	diamondBoots: 0,
};

const v11 = {
	axe: '<:Wooden_Axe:817217337261424650>',
	pickaxe: '<:Wooden_Pickaxe:817217441394196572>',
	rod: '<:Wooden_Rod:816598231509237810>',

	cobblestone: 0,
	coal: 0,
	ironOre: 0,
	iron: 0,
	goldOre: 0,
	gold: 0,
	lapis: 0,
	diamond: 0,
	pureDiamond: 0,
	
	mine: 'starter_mine',
	mineLevel: 0,
	mineXp: 0,

	fishLevel: 0,
	fishXp: 0,

	chopLevel: 0,
	chopXp: 0,

	oakWood: 0,
	birchWood: 0,
	darkOakWood: 0,
	spruceWood: 0,
	acaciaWood: 0,
	jungleWood: 0,
	planks: 0,
	stick: 0,

	forest: true,
	roofedForest: false,
	taiga: false,
	savannah: false,
	jungle: false,

	commonFish: 0,
	uncommonFish: 0,
	rareFish: 0,
	ultraRareFish: 0,
	legendaryFish: 0,
	
	coins: 0,
	bank: 0,
	netWorth: 0,

	invOakWoodMinion: 0,
	invBirchWoodMinion: 0,
	invDarkOakWoodMinion: 0,
	invSpruceWoodMinion: 0,
	invAcaciaWoodMinion: 0,
	invJungleWoodMinion: 0,
	invCobblestoneMinion: 0,
	invCoalMinion: 0,
	invIronMinion: 0,
	invGoldMinion: 0,
	invDiamondMinion: 0,
	invLapisMinion: 0,

	placedMinions: [
		[
			'cobblestone minion',
			'invCobblestoneMinion',
			'i',
			'<:Placed_Cobblestone_Minion:887166926948798484>',
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			1650340892852,
			'cobblestone minion'
		]
	],

	bankTier: 1,
	enchantedGold: 0,
	enchantedGoldBlock: 0,
	blockOfCoal: 0,
	enchantedBread: 0,
	enchantedCharcoal: 0,
	enchantedCoal: 0,
	enchantedLavaBucket: 0,
	enchantedCobblestone: 0,
	enchantedIron: 0,
	enchantedLapis: 0,
	enchantedDiamond: 0,
	enchantedOakWood: 0,
	enchantedBirchWood: 0,
	enchantedDarkOakWood: 0,
	enchantedSpruceWood: 0,
	enchantedAcaciaWood: 0,
	enchantedJungleWood: 0,
	redstone: 0,
	enchantedRedstone: 0,
	compactor: 0,
	superCompactor: 0,
	invRedstoneMinion: 0,
	tutorials: { minion: false, dices: false, highlow: false, scratchoff: false },
	gambleStats: {
		dices: { moneyWon: 0, moneyLost: 0, totalWins: 0, totalLoses: 0 },
		scratchoff: { moneyWon: 0, moneyLost: 0, totalWins: 0, totalLoses: 0 }
	},
	sword: {
		name: 'Wooden sword',
		keyName: 'woodenSword',
		emoji: '<:Wooden_Sword:945957542280970300>',
		baseDamage: 20,
		enchantments: []
	},
	woodenSword: 0,
	stoneSword: 0,
	ironSword: 0,
	goldSword: 0,
	diamondSword: 0,
	aspectOfTheSpiritButterfly: 0,
	spiritButterfly: 0,

	woodenPickaxe: 0,
	stonePickaxe: 0,
	ironPickaxe: 0,
	goldPickaxe: 0,
	diamondPickaxe: 0,

	woodenAxe: 0,
	stoneAxe: 0,
	ironAxe: 0,
	goldAxe: 0,
	diamondAxe: 0,

	combatLevel: 0,
	combatXp: 0,

	activeItems: [],
	fourLeafClover: 0,
	stopwatch: 0,
	achievements: [
		{
			id: `use1kCmds`,
			done: false
		},
		{
			id: `use10kCmds`,
			done: false
		},
		{
			id: `use50kCmds`,
			done: false
		},
		{
			id: `use100kCmds`,
			done: false
		}
	],
	adventure: {},
	commandUses: {},
	start: true,
	update: '11.0.0',

	enclosure: 'cow',
	piggyBank: 0,
	crackedPiggyBank: 0,
	brokenPiggyBank: 0,
	rawPorkchop: 0,
	enchantedPork: 0,
	enchantedGrilledPork: 0,
	rawChicken: 0,
	enchantedRawChicken: 0,
	rawBeef: 0,
	enchantedRawBeef: 0,
	rawMutton: 0,
	enchantedMutton: 0,
	enchantedCookedMutton: 0,

	settings: [
		{ setting: 'hideFromLb', value: false },
		{ setting: 'fightNerd', value: false },
		{ setting: 'voteReady', value: false }
	],
	daily: { lastClaimed: 0, streak: 0 },

	adventureTicket: 0,
	hiltOfTheSeas: 0,
	firstFragmentOfTheSeas: 0,
	secondFragmentOfTheSeas: 0,
	aspectOfTheSeas: 0,
	dummy: 0,

	helmet: null,
	chestplate: null,
	leggings: null,
	boots: null,

	leatherHelmet: 0,
	leatherChestplate: 0,
	leatherLeggings: 0,
	leatherBoots: 0,

	ironHelmet: 0,
	ironChestplate: 0,
	ironLeggings: 0,
	ironBoots: 0,

	goldHelmet: 0,
	goldChestplate: 0,
	goldLeggings: 0,
	goldBoots: 0,

	diamondHelmet: 0,
	diamondChestplate: 0,
	diamondLeggings: 0,
	diamondBoots: 0,

	protectorDragonHelmet: 0,
	protectorDragonChestplate: 0,
	protectorDragonLeggings: 0,
	protectorDragonBoots: 0,
	protectorDragonFragment: 0,

	oldDragonHelmet: 0,
	oldDragonChestplate: 0,
	oldDragonLeggings: 0,
	oldDragonBoots: 0,
	oldDragonFragment: 0,
	
	wiseDragonHelmet: 0,
	wiseDragonChestplate: 0,
	wiseDragonLeggings: 0,
	wiseDragonBoots: 0,
	wiseDragonFragment: 0,

	unstableDragonHelmet: 0,
	unstableDragonChestplate: 0,
	unstableDragonLeggings: 0,
	unstableDragonBoots: 0,
	unstableDragonFragment: 0,

	youngDragonHelmet: 0,
	youngDragonChestplate: 0,
	youngDragonLeggings: 0,
	youngDragonBoots: 0,
	youngDragonFragment: 0,

	strongDragonHelmet: 0,
	strongDragonChestplate: 0,
	strongDragonLeggings: 0,
	strongDragonBoots: 0,
	strongDragonFragment: 0,

	superiorDragonHelmet: 0,
	superiorDragonChestplate: 0,
	superiorDragonLeggings: 0,
	superiorDragonBoots: 0,
	superiorDragonFragment: 0,
	
	summoningEye: 0,
	remnantOfTheEye: 0
};

const v12 = {
	axe: '<:Wooden_Axe:817217337261424650>',
	pickaxe: '<:Wooden_Pickaxe:817217441394196572>',
	rod: '<:Wooden_Rod:816598231509237810>',

	cobblestone: 0,
	coal: 0,
	ironOre: 0,
	iron: 0,
	goldOre: 0,
	gold: 0,
	lapis: 0,
	diamond: 0,
	pureDiamond: 0,
	
	mine: 'starter_mine',
	mineLevel: 0,
	mineXp: 0,

	fishLevel: 0,
	fishXp: 0,

	chopLevel: 0,
	chopXp: 0,

	oakWood: 0,
	birchWood: 0,
	darkOakWood: 0,
	spruceWood: 0,
	acaciaWood: 0,
	jungleWood: 0,
	planks: 0,
	stick: 0,

	forest: true,
	roofedForest: false,
	taiga: false,
	savannah: false,
	jungle: false,

	commonFish: 0,
	uncommonFish: 0,
	rareFish: 0,
	ultraRareFish: 0,
	legendaryFish: 0,
	
	coins: 0,
	bank: 0,
	netWorth: 0,

	invOakWoodMinion: 0,
	invBirchWoodMinion: 0,
	invDarkOakWoodMinion: 0,
	invSpruceWoodMinion: 0,
	invAcaciaWoodMinion: 0,
	invJungleWoodMinion: 0,
	invCobblestoneMinion: 0,
	invCoalMinion: 0,
	invIronMinion: 0,
	invGoldMinion: 0,
	invDiamondMinion: 0,
	invLapisMinion: 0,

	placedMinions: [
		[
			'cobblestone minion',
			'invCobblestoneMinion',
			'i',
			'<:Placed_Cobblestone_Minion:887166926948798484>',
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			1650340892852,
			'cobblestone minion'
		]
	],

	bankTier: 1,
	enchantedGold: 0,
	enchantedGoldBlock: 0,
	blockOfCoal: 0,
	enchantedBread: 0,
	enchantedCharcoal: 0,
	enchantedCoal: 0,
	enchantedLavaBucket: 0,
	enchantedCobblestone: 0,
	enchantedIron: 0,
	enchantedLapis: 0,
	enchantedDiamond: 0,
	enchantedOakWood: 0,
	enchantedBirchWood: 0,
	enchantedDarkOakWood: 0,
	enchantedSpruceWood: 0,
	enchantedAcaciaWood: 0,
	enchantedJungleWood: 0,
	redstone: 0,
	enchantedRedstone: 0,
	compactor: 0,
	superCompactor: 0,
	invRedstoneMinion: 0,
	tutorials: { minion: false, dices: false, highlow: false, scratchoff: false },
	gambleStats: {
		dices: { moneyWon: 0, moneyLost: 0, totalWins: 0, totalLoses: 0 },
		scratchoff: { moneyWon: 0, moneyLost: 0, totalWins: 0, totalLoses: 0 }
	},
	sword: {
		name: 'Wooden sword',
		keyName: 'woodenSword',
		emoji: '<:Wooden_Sword:945957542280970300>',
		baseDamage: 20,
		enchantments: []
	},
	woodenSword: 0,
	stoneSword: 0,
	ironSword: 0,
	goldSword: 0,
	diamondSword: 0,
	aspectOfTheSpiritButterfly: 0,
	spiritButterfly: 0,

	woodenPickaxe: 0,
	stonePickaxe: 0,
	ironPickaxe: 0,
	goldPickaxe: 0,
	diamondPickaxe: 0,

	woodenAxe: 0,
	stoneAxe: 0,
	ironAxe: 0,
	goldAxe: 0,
	diamondAxe: 0,

	combatLevel: 0,
	combatXp: 0,

	activeItems: [],
	fourLeafClover: 0,
	stopwatch: 0,
	achievements: [
		{
			id: `use1kCmds`,
			done: false
		},
		{
			id: `use10kCmds`,
			done: false
		},
		{
			id: `use50kCmds`,
			done: false
		},
		{
			id: `use100kCmds`,
			done: false
		}
	],
	adventure: {},
	commandUses: {},
	start: true,
	update: '11.0.0',

	enclosure: 'cow',
	piggyBank: 0,
	crackedPiggyBank: 0,
	brokenPiggyBank: 0,
	rawPorkchop: 0,
	enchantedPork: 0,
	enchantedGrilledPork: 0,
	rawChicken: 0,
	enchantedRawChicken: 0,
	rawBeef: 0,
	enchantedRawBeef: 0,
	rawMutton: 0,
	enchantedMutton: 0,
	enchantedCookedMutton: 0,

	settings: [
		{ setting: 'incognito', value: false },
		{ setting: 'fightNerd', value: false },
		{ setting: 'voteReady', value: false }
	],
	daily: { lastClaimed: 0, streak: 0 },

	adventureTicket: 0,
	hiltOfTheSeas: 0,
	firstFragmentOfTheSeas: 0,
	secondFragmentOfTheSeas: 0,
	aspectOfTheSeas: 0,
	dummy: 0,

	helmet: null,
	chestplate: null,
	leggings: null,
	boots: null,

	leatherHelmet: 0,
	leatherChestplate: 0,
	leatherLeggings: 0,
	leatherBoots: 0,

	ironHelmet: 0,
	ironChestplate: 0,
	ironLeggings: 0,
	ironBoots: 0,

	goldHelmet: 0,
	goldChestplate: 0,
	goldLeggings: 0,
	goldBoots: 0,

	diamondHelmet: 0,
	diamondChestplate: 0,
	diamondLeggings: 0,
	diamondBoots: 0,

	protectorDragonHelmet: 0,
	protectorDragonChestplate: 0,
	protectorDragonLeggings: 0,
	protectorDragonBoots: 0,
	protectorDragonFragment: 0,

	oldDragonHelmet: 0,
	oldDragonChestplate: 0,
	oldDragonLeggings: 0,
	oldDragonBoots: 0,
	oldDragonFragment: 0,
	
	wiseDragonHelmet: 0,
	wiseDragonChestplate: 0,
	wiseDragonLeggings: 0,
	wiseDragonBoots: 0,
	wiseDragonFragment: 0,

	unstableDragonHelmet: 0,
	unstableDragonChestplate: 0,
	unstableDragonLeggings: 0,
	unstableDragonBoots: 0,
	unstableDragonFragment: 0,

	youngDragonHelmet: 0,
	youngDragonChestplate: 0,
	youngDragonLeggings: 0,
	youngDragonBoots: 0,
	youngDragonFragment: 0,

	strongDragonHelmet: 0,
	strongDragonChestplate: 0,
	strongDragonLeggings: 0,
	strongDragonBoots: 0,
	strongDragonFragment: 0,

	superiorDragonHelmet: 0,
	superiorDragonChestplate: 0,
	superiorDragonLeggings: 0,
	superiorDragonBoots: 0,
	superiorDragonFragment: 0,
	
	summoningEye: 0,
	remnantOfTheEye: 0,

	subareaUnlocks: []
};



exports.v9 = v9;
exports.v10 = v10;
exports.v11 = v11;
exports.v12 = v12;